parameters:
    rheck.access_control.security_context.adapter.class: Rheck\AccessControlBundle\Adapter\SecurityContextAdapter

    rheck.access_control.access_control.annotation_driver.class: Rheck\AccessControlBundle\Driver\AccessControlDriver

    rheck.access_control.access.control.service.class:     Rheck\AccessControlBundle\Service\AccessControlService
    rheck.access_control.permission.service.class:         Rheck\AccessControlBundle\Service\PermissionService
    rheck.access_control.permission_context.service.class: Rheck\AccessControlBundle\Service\PermissionContextService

    rheck.access_control.default.strategy.class: Rheck\AccessControlBundle\Strategy\PermissionAccess\DefaultPermissionAccessStrategy

    rheck.access_control.access.control.extension.class: Rheck\AccessControlBundle\Extension\AccessControlExtension

services:
    rheck.access_control.security_context.adapter:
        class: %rheck.access_control.security_context.adapter.class%
        calls:
            - [setSecurityContext, ["@security.context"]]

    rheck.access_control.access_control.annotation_driver:
        class:     %rheck.access_control.access_control.annotation_driver.class%
        arguments: [@annotation_reader, @rheck.access_control.access.control.service]
        tags:
            -  { name: kernel.event_subscriber }

    rheck.access_control.access.control.service:
        class:     %rheck.access_control.access.control.service.class%
        arguments: [@service_container]

    rheck.access_control.permission.service:
        class:     %rheck.access_control.permission.service.class%
        arguments: [@doctrine.orm.entity_manager, @rheck.access_control.permission_context.service]

    rheck.access_control.permission_context.service:
        class:     %rheck.access_control.permission_context.service.class%
        arguments: [@doctrine.orm.entity_manager]

    rheck.access_control.default.strategy:
        class:     %rheck.access_control.default.strategy.class%
        calls:
            - [setSecurityContextAdapter, ["@rheck.access_control.security_context.adapter"]]
            - [setPermissionService, ["@rheck.access_control.permission.service"]]
            - [setHasPermissions, ["%rheck_access_control.has_permissions%"]]

    rheck.access_control.access.control.extension:
        class:  %rheck.access_control.access.control.extension.class%
        arguments:  [@rheck.access_control.access.control.service]
        tags:
            -  { name: twig.extension }