before_commands:
    - composer install --dev
tools:
    php_cs_fixer: true
    php_code_coverage:
        enabled: true
        filter:
            excluded_paths: ["vendor/*"]
    php_mess_detector: 
        enabled: true
        filter:
            excluded_paths: ["vendor/*"]
    php_analyzer:
        enabled: true
        filter:
            excluded_paths: ["vendor/*"]
